name: unittest

on: [push,pull_request]

env:
  GITHUB_WORKSPACE: /home/testdir

jobs:
  unittest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install BLMM
        run: pip install -e .[all]     

      - name: Run Test
        run: pytest BLMM/test/Unit/*
  
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install BLMM
        run: pip install -e .[tests] && sudo apt-get update && sudo apt-get install make 

      - name: Run Test
        run: make lint

  integrationtest:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: setup-conda
        run: |
          cd $GITHUB_WORKSPACE 
          mkdir data
          conda create -n testenv python=${{ matrix.python-version }} 
          source activate testenv 

      - name: install-repo
        run: |
          pip install -e .[all]

      - name: generate-data
        run: |
          bash BLMM/test/Integration/generateData.sh $GITHUB_WORKSPACE/data 1 1

      - name: Run Test
        run: |
          pytest BLMM/test/Integration/*.py

      - name: cleanup
        run: |
          conda deactivate
          conda env remove -n testenv 